# This workflow is designed for a monorepo with separate frontend and backend directories.
# It ensures that each project is built and tested independently.

name: DigiSoal CI

# This workflow will run on pushes and pull requests to the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This job handles the backend (Node.js server) build and test
  backend-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    # Run npm commands within the 'backend' directory
    - name: Install backend dependencies
      run: npm ci
      working-directory: ./backend

    - name: Run backend tests
      run: npm test
      working-directory: ./backend

  # This job handles the frontend (React app) build and test
  frontend-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    # Run npm commands within the 'frontend' directory
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend application
      run: npm run build --if-present
      working-directory: ./frontend
    
    - name: Run frontend tests
      run: npm test
      working-directory: ./frontend
